config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'registration/sign_in'

  get 'home/katalogs'
  get 'home/product'
  get 'home/about'
  get 'registratino/sign_in'
  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :mevas
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/models/meva.rb
class Meva < ActiveRecord::Base
  belongs_to :sprod
  belongs_to :city
  belongs_to :unit
  mount_uploader :decript_photo, DescriptPhotoProductUploader
end

app/models/prod.rb
class Prod < ActiveRecord::Base
  has_many :sprods
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :photo, DescriptPhotoProductUploader

end

app/models/sprod.rb
class Sprod < ActiveRecord::Base
  belongs_to :prod
  has_many :mevas
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :mevas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :get_kategory

  private
  def get_kategory
    @frute = Prod.find_by_name('Фрукты').id
    @frut_subcategory = Sprod.all.where(prod_id:[@frute])

    @sfrute = Prod.find_by_name('Сухофрукты').id
    @sfrut_subcategory = Sprod.all.where(prod_id:[@sfrute])

    @ovoshi = Prod.find_by_name('Овощы').id
    @ovoshi_subcategory = Sprod.all.where(prod_id:[@ovoshi])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @best_product = Meva.order(reting: :desc).limit(4)
    @slide = Slider.all
  end

  def katalogs
    @product = Meva.all
  end

  def product
 #   @prod = Meva.find(params[:id])
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def sign_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/about.html.erb
<section class="about">
  <div class="col-md-3 col-sm-3">
    <%= render 'layouts/menu' %>

    <div class="question">
      <div class="question_headling">
        <div class="question_icon"></div>
        <h2>Есть вопросы?</h2>
        <p>Мы вам поможем!</p>
      </div>
      <button>Задать вопрос</button>
    </div>

  </div>
  <div class="col-md-9 col-sm-9">
    <div class="katalog_link">
      <a href="" id="katalog_link_to_main"></a><a href="">О Компании</a>
    </div>
    <div class="clear"></div>

    <div class="headling">О компании</div>

    <%= image_tag 'about.jpg' %>

    <p>Компания ШЁЛКОВЫЙ ПУТЬ – крупнейший поставщик комплексных решений для промышленных предприятий России.
      Мы оснащаем предприятия всем необходимым, выполняя функции внешнего отдела снабжения.
    </p>

    <p>Наша компания поставляет автоматизированные системы управления, контрольно-измерительные приборы, вычислительную технику,
      аналитические приборы, лабораторное и весовое оборудование, расходные материалы и многое другое.
      Ассортимент поставляемой нами продукции постоянно растет и сейчас включает в себя несколько тысяч позиций.
    </p>

    <p>
      Уже более двухсот компаний-производителей являются нашими партнёрами.
      Среди них такие компании как Mettler Toledo, Siemens, Fuji Electric, IBM, HP.
    </p>

    <div class="why_we">
      <h2>Почему именно мы?</h2>

      <ul>
        <li><span>Качественные продукты</span> </li>
        <li><span>Большой масштаб покрытия</span></li>
        <li><span>Постоянное пополнение</span></li>
      </ul>
    </div>
  </div>
  <div class="clear"></div>

</section>

app/views/home/index.html.erb
<section class="main_page">
  <div class="row">
    <div class="col-md-3 col-sm-3">
      <%= render 'layouts/menu' %>

      <div class="question">
        <div class="question_headling">
          <div class="question_icon"></div>
          <h2>Есть вопросы?</h2>
          <p>Мы вам поможем!</p>
        </div>
        <button>Задать вопрос</button>

      </div>
    </div>
    <div class="col-md-9 col-sm-9">
      <div class="slider_container">

      <% @slide.each do |slide| %>
        <div class="slide" style="background-image: url(<%= slide.photo %>)">
          <div class="slider_headling">
            <h2><%= slide.title %></h2>
          </div>
          <div class="slider_desctription">
            <p><%= slide.description %></p>
          </div>
        </div>
      <% end %>

      </div>
    </div>
  </div>

  <div class="headling">ЛУЧШИЕ ТОВАРЫ</div>
  <div class="row best_products">

    <% @best_product.each do |tovar| %>
        <div class="col-md-3 col-sm-3">

            <div class="best_product">
              <h3> <%= link_to tovar.name, home_product_path(tovar)%></h3>
              <div class="product_photo" style="background-image: url('<%= tovar.decript_photo %>')">

              </div>

              <div class="product_price"><%= tovar.price %><%= tovar.unit.name %></div>
              <div class="product_adress">Место склада: <span><%= tovar.city.name %></span></div>
            </div>
            <div class="more_broduct"><%= link_to 'Больше товаров', home_katalogs_url %></div>

        </div>
    <% end %>

  </div>

</section>

app/views/home/katalogs.html.erb
<section class="katalog_page" xmlns="http://www.w3.org/1999/html">
  <div class="col-md-3 col-sm-3">
    <%= render 'layouts/menu' %>

    <div class="block_filther">
      <div class="price_text">Цена, руб.</div>
      <input type="text" id="minCost" value="0"/>
      —
      <input type="text" id="maxCost" value="1000"/>

      <div class="price_text" id="filter_city">Место склада (город)</div>

      <select id="select_city">
        <option>Кемерово (Россия)</option>
        <option>Душанбе (Таджикистан)</option>
        <option>Исфара (Россия)</option>
      </select>

      <div class="in_stock">
        <input type="checkbox" checked> <span>Есть в наличии</span>
      </div>
      <div class="only_with_photo">
        <input type="checkbox" checked> <span>с фото</span>
      </div>

      <button id="filter_show">Показать</button>
      <button id="filter_restart">Сбросить</button>
    </div>
  </div>

  <div class="col-md-9 col-sm-9">

      <div class="katalog_link">
        <a href="" id="katalog_link_to_main"></a><a href="">Каталог</a><a href="">Фрукты</a>
      </div>

    <div class="sortirovka">
        <span> Сортировать по</span>
        <span> Рейтингу</span>
        <span class="sortirovka_active"> Цене</span>
        <span> Дате</span>
    </div>

    <% @product.each do |prod| %>
    <div class="col-md-4 col-sm-4">
      <div class="product">

        <h2><%= prod.name %></h2>
        <div class="reting">
          <div class="star"></div>
          <div class="star"></div>
          <div class="star"></div>
          <div class="star"></div>
        </div>
        <div class="product_photo" style="background-image: url(<%= prod.decript_photo %>)"></div>
        <div class="product_price"><%= prod.price %></div>
        <div class="product_adress">Место склада: <span><%= prod.city.name %></span></div>
        <%= link_to 'Подробнее', home_product_url %>
      </div>
    </div>
    <% end %>

    <div class="clear"></div>

    <div class="prev_next_page">
      <div class="prev"></div>
      <div class="page_number">1</div>
      <div class="page_number active_page">2</div>
      <div class="page_number">3</div>
      <div class="next"></div>
    </div>
  </div>

<div class="clear"></div>

</section>

app/views/home/product.html.erb
<section class="product_item">
  <div class="col-md-3 col-sm-3">
    <%= render 'layouts/menu' %>
   </div>

  <div class="col-md-9 col-sm-9">
    <div class="katalog_link">
      <a href="" id="katalog_link_to_main"></a><a href="">Каталог</a><a href="">Фрукты</a><a href=""> Бананы</a>
    </div>
    <div class="clear"></div>
  </div>

  <div class="col-md-4 col-sm-4">
    <div class="product_slider"></div>
</div>

  <div class="col-md-5 col-sm-5">
    <div class="product_name">Бананы Лакатан</div>

    <div class="reting" id="product_item_reting">
      <div class="star"></div>
      <div class="star"></div>
      <div class="star"></div>
      <div class="star"></div>
    </div>
    <div class="clear"></div>
    <div class="product_prise">80 руб./кг</div>

    <div class="product_amount">
      <span>Количество</span>

      <input type="number" value="1"/>
      <span>кг (доступно 120 кг)</span>
    </div>

    <div class="seller_adreess">
      <div class="seller_address_leble">Место склада</div>
      <div class="seller_address_name">Ташкент(Узбекистан)</div>
    </div>

    <form action="" id="product_form">
      <button>Купить</button>
      <button>В корзину</button>
    </form>

    <div class="product_seller">
      <div class="seller_leble">Продавец</div>
      <div class="seller_name">ООО "АзияФрукт"</div>
    </div>

    <div class="seller_phone_cont">
      <div class="seller_phone_leble"> Телефон продавца</div>
      <div class="seller_phone">+7 923 720 2020</div>
    </div>

    <div class="product_description">
      <div class="product_description_lable">Описание</div>
      <div class="product_description_text">
        Бананы — одна из древнейших пищевых культур,
        а для тропических стран важнейшее пищевое растение и главная статья экспорта.
        Спелые бананы широко употребляются в пищу по всему миру, их используют при приготовлении большого количества блюд.
      </div>
    </div>

    <div class="product_more_info">
      <div class="product_more_info_lable">Дополнительная
      информация</div>
      <div class="product_more_info_text">Бананы могут зажариваться, или вариться как в очищенном, так и в неочищенном виде.</div>
    </div>
  </div>
<div class="clear"></div>
</section>

app/views/layouts/_footer.html.erb
<section class="footer">
  <div class="col-md-6 col-sm-6">
    <div class="logo">ШЁЛКОВЫЙ ПУТЬ</div>
    <div class="logo_description">Торговая площадка для предпринимателей</div>
  </div>

  <div class="col-md-6 col-sm-6">
    <div class="footer_menu">
      <ul>
        <li><a href="">Фрукты</a></li>
        <li><a href="">Сухофрукты</a></li>
        <li><a href="">Овощи</a></li>
      </ul>
    </div>

    <div class="footer_contacts">
      <div class="mail">sholkovi_put@gmail.com</div>
      <div class="tel">8 800 233 445</div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<section class="header">

  <div class="row">
    <div class="col-md-4 col-sm-4">
      <a href="/" class="logo">ШЁЛКОВЫЙ ПУТЬ</a>
      <div class="logo_description">Торговая площадка для предпринимателей</div>
    </div>
    <div class="col-md-8 col-sm-8 header_btns">

      <form action="" class="header_search">
        <input type="text"/>
        <button type="submit"></button>
      </form>

      <a href="/home/about" class="about_us">О нас</a>
      <button class="korzina">Корзина</button>
      <div class="sign_in">
        Войти

        <div class="sign_in_form">
          <form action="" name="sign_in">
            <input type="text" placeholder="Ваш логин"/>
            <input type="text" placeholder="Ваш пароль"/>
            <button>Войти</button>
          </form>

          <a href="/registration/sign_in">Зарегистрироваться</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_menu.html.erb
<section class="main_menu">
  <h2>Каталог</h2>
  <nav>
    <a id="frut">Фрукты</a>
    <div class="frut">
      <ul>
        <% @frut_subcategory.each do |subcategory| %>
            <li>
              <%= link_to subcategory.name, home_katalogs_url %>
            </li>
        <% end %>
      </ul>
    </div>
    <a id="sfrut">Сухофрукты</a>
    <div class="sfrut">
      <ul>
        <% @sfrut_subcategory.each do |subcategory| %>
             <li>
               <%= link_to subcategory.name, home_katalogs_url %>
             </li>
        <% end %>
      </ul>
    </div>
    <a id="vegetables">Овощи</a>
    <div class="vegetables">
      <ul>
        <% @ovoshi_subcategory.each do |subcategory| %>
            <li>
              <%= link_to subcategory.name, home_katalogs_url %>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Шелковый путь</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wper-1">
  <div class="container">
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
</div>

</body>
</html>